image: maven:latest

stages:
  - build

build:
  stage: build
  script:
    - mvn package
    - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=morningstar
  only:
    changes:
      - src/**/*
      - pom.xml
  artifacts:
    expire_in: 2 weeks
    paths:
      - target/Habbo-*.jar
  
